# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

# theme: jekyll-theme-console

title: "beiciliang.github.io"
description: "Beici Liang's Personal Website"
url: "https://beiciliang.github.io"

header_pages:
  - index.md

style: dark

footer: 'drop me an <a target="_blank" rel="noopener noreferrer" href="mailto:beici.liang@foxmail.com">email</a>'

# Build settings
markdown: kramdown
